batch_size: 8
gradient_accumulation_steps: 4
lr: 2.0e-4
warm_up: 0.01
warm_up_iters: 100
lora_r: 16
lora_alpha: 32
epochs: 1000
save_interval: 3000
log_interval: 1
bmt_cpu_offload: False
bmt_pre_load: True

save_optim: True
save_rng: True
lora: True

enable_sft_dataset_dir: './data/'
enable_sft_dataset_file: 'convo_samples.jsonl'
