batch_size: 2
gradient_accumulation_steps: 1
lr: 3.0e-4
warm_up: 0.01
warm_up_iters: 100
lora_r: 64
lora_alpha: 512
epochs: 1000
save_interval: 2000
log_interval: 1
bmt_cpu_offload: False
bmt_pre_load: True

save_optim: True
save_rng: True
lora: True

enable_sft_dataset_dir: './data/'
enable_sft_dataset_file: 'convo_v2.jsonl'
