# comments
batch_size: 4
gradient_accumulation_steps: 1
lr: 1.2e-4
warm_up: 0.01
save_interval: 500 
weight_decay: 0.1

bmt_cpu_offload: False
bmt_pre_load: False 
bmt_async_load: True 
# bmt_loss_scale: 65536 
bmt_loss_scale: 65536.0

save_optim: False
save_rng: False

# load_dir: '/share/project/64node-bmt-flashatten/checkpoints/Aquila-30b-64n8g-from-scratch'
load_optim: False 
resume_dataset: False
bmt_lr_decay_style: 'consine'
# warm_up_iters: 2000
# iteration_in_epoch: 9000


